// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzwC1B4cFcu-7Y1ChCH-GLz76IAS5nibo',
    appId: '1:369804060656:web:eae3062285956096031f35',
    messagingSenderId: '369804060656',
    projectId: 'travel-app-23',
    authDomain: 'travel-app-23.firebaseapp.com',
    storageBucket: 'travel-app-23.firebasestorage.app',
    measurementId: 'G-EXCMZ27KRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Hn5r-MBXmT1C3D-1pQhURdAWnHQ3B-0',
    appId: '1:369804060656:android:d76d221308cbb57f031f35',
    messagingSenderId: '369804060656',
    projectId: 'travel-app-23',
    storageBucket: 'travel-app-23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW8UFA8J006iCNzW5H5X9hgmpMpqjlCNE',
    appId: '1:369804060656:ios:d528494cacbbfcab031f35',
    messagingSenderId: '369804060656',
    projectId: 'travel-app-23',
    storageBucket: 'travel-app-23.firebasestorage.app',
    iosClientId: '369804060656-ksd9kecmi3hgs51mqa2rrpcfgtmtkdij.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW8UFA8J006iCNzW5H5X9hgmpMpqjlCNE',
    appId: '1:369804060656:ios:d528494cacbbfcab031f35',
    messagingSenderId: '369804060656',
    projectId: 'travel-app-23',
    storageBucket: 'travel-app-23.firebasestorage.app',
    iosClientId: '369804060656-ksd9kecmi3hgs51mqa2rrpcfgtmtkdij.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzwC1B4cFcu-7Y1ChCH-GLz76IAS5nibo',
    appId: '1:369804060656:web:4a2bbd0afe66ed6a031f35',
    messagingSenderId: '369804060656',
    projectId: 'travel-app-23',
    authDomain: 'travel-app-23.firebaseapp.com',
    storageBucket: 'travel-app-23.firebasestorage.app',
    measurementId: 'G-3DRZ2VYKW5',
  );

}