// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsjtAhjNAAJCHsVhQxq8eLsmWAGDvD2sM',
    appId: '1:594361835820:web:8e28aaa33dc0c9a471cc89',
    messagingSenderId: '594361835820',
    projectId: 'nth-autumn-458710-t7',
    authDomain: 'nth-autumn-458710-t7.firebaseapp.com',
    storageBucket: 'nth-autumn-458710-t7.firebasestorage.app',
    measurementId: 'G-3TQE9PSE2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJua6mzX_YUxeZ-5EWyo7l-crMh7Do0sM',
    appId: '1:594361835820:android:0f42dccbf361908871cc89',
    messagingSenderId: '594361835820',
    projectId: 'nth-autumn-458710-t7',
    storageBucket: 'nth-autumn-458710-t7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7hT49LbgPCc8Racvs08d72pbvPh3BgeI',
    appId: '1:594361835820:ios:811edb0ab8ab1d3f71cc89',
    messagingSenderId: '594361835820',
    projectId: 'nth-autumn-458710-t7',
    storageBucket: 'nth-autumn-458710-t7.firebasestorage.app',
    androidClientId: '594361835820-47ufplfqrpco91g2ht650q10j5nftb8m.apps.googleusercontent.com',
    iosClientId: '594361835820-6b113iki8j2ruqd5cblc9n88mqa5qnti.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7hT49LbgPCc8Racvs08d72pbvPh3BgeI',
    appId: '1:594361835820:ios:811edb0ab8ab1d3f71cc89',
    messagingSenderId: '594361835820',
    projectId: 'nth-autumn-458710-t7',
    storageBucket: 'nth-autumn-458710-t7.firebasestorage.app',
    androidClientId: '594361835820-47ufplfqrpco91g2ht650q10j5nftb8m.apps.googleusercontent.com',
    iosClientId: '594361835820-6b113iki8j2ruqd5cblc9n88mqa5qnti.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsjtAhjNAAJCHsVhQxq8eLsmWAGDvD2sM',
    appId: '1:594361835820:web:921c3332d5e37edf71cc89',
    messagingSenderId: '594361835820',
    projectId: 'nth-autumn-458710-t7',
    authDomain: 'nth-autumn-458710-t7.firebaseapp.com',
    storageBucket: 'nth-autumn-458710-t7.firebasestorage.app',
    measurementId: 'G-X34VQS5KPV',
  );

}